# Generated by Django 3.1.7 on 2021-04-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_remove_bookmark_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='folder_name',
            field=models.ManyToManyField(blank=True, default=None, to='homepage.Folder'),
        ),
    ]
