# Generated by Django 3.2 on 2021-04-15 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_bookmark_folder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='folder_name',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='folder_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.folder'),
        ),
    ]
